/**
 * Bakes the handful of brand marks the Skills section needs into
 * `src/lib/logos.js`.
 *
 * simple-icons is a dev dependency and stays one: importing it at runtime pulls
 * a few thousand icons into the bundle to use eleven of them. This lifts out
 * the paths we actually reference, so the app ships ~10 path strings and no
 * dependency at all.
 *
 * Re-run with `npm run logos` after editing SKILL_ICONS.
 */
import * as si from "simple-icons";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

/** our slug -> simple-icons export. React Native's mark is React's atom. */
const SKILL_ICONS = {
  react: "siReact",
  nextjs: "siNextdotjs",
  reactnative: "siReact",
  flutter: "siFlutter",
  nodejs: "siNodedotjs",
  python: "siPython",
  fastapi: "siFastapi",
  postgresql: "siPostgresql",
  docker: "siDocker",
  langchain: "siLangchain",
  langgraph: "siLanggraph",
  claude: "siClaude"
  // No `aws`: simple-icons dropped Amazon's marks over their trademark policy.
  // Skills falls back to a lettered tile rather than an invented logo.
};

/** Relative luminance, for the black-on-black problem below. */
function luminance(hex) {
  const n = parseInt(hex, 16);
  const c = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
}

const out = {};
const missing = [];

for (const [slug, key] of Object.entries(SKILL_ICONS)) {
  const icon = si[key];
  if (!icon) {
    missing.push(`${slug} (${key})`);
    continue;
  }
  /* Several marks are pure black -- Next.js, Vercel, Express. On this page's
     ground that is an invisible logo, so anything too dark to see is carried
     as white instead. The brand colour is only ever used as a hover accent, so
     substituting keeps the interaction rather than losing it. */
  const dark = luminance(icon.hex) < 0.06;
  out[slug] = {
    title: icon.title,
    path: icon.path,
    hex: dark ? "FFFFFF" : icon.hex
  };
}

if (missing.length) {
  console.error("Not found in simple-icons:", missing.join(", "));
  process.exit(1);
}

const here = dirname(fileURLToPath(import.meta.url));
const dest = join(here, "..", "src", "lib", "logos.js");

const body = Object.entries(out)
  .map(([slug, v]) =>
    `  ${slug}: {\n    title: ${JSON.stringify(v.title)},\n    hex: "#${v.hex}",\n    path: ${JSON.stringify(v.path)}\n  }`
  )
  .join(",\n");

writeFileSync(
  dest,
  `/* GENERATED by scripts/build-logos.mjs -- do not edit by hand.
 *
 * Brand marks from simple-icons (CC0), carried as raw path data in a 24x24
 * viewBox. Each is the trademark of its owner and appears here only to name a
 * tool the team works with.
 */
export const logos = {
${body}
};
`,
  "utf8"
);

console.log(`wrote ${Object.keys(out).length} marks to src/lib/logos.js`);
